export const petitionActions = {
    SET_LOGIN_STATE: "SET_USER_LOGIN_STATE",
    SET_REGISTER_STATE: "SET_REGISTER_STATE",
    SET_LOGOUT_STATE:"SET_LOGOUT_STATE",
    SET_ALL_PETITIONS: "SET_ALL_PETITIONS",
    SET_SINGLE_PETITIONS: "SET_SINGLE_PETITIONS",
    SET_CREATE_USER_PETITIONS: "SET_CREATE_USER_PETITIONS",
    SET_ALL_USER_PETITIONS: "SET_ALL_USER_PETITIONS",
    SET_SIGNATURE_PETITIONS: "SET_SIGNATURE_PETITIONS",

   
  };